# Multi_Nomial_NB

There are three types of naive bayes ... 1-Bernoli NB -> when all the features are of binary , where word exists or not ... 2-MultinomialNB -> when the data is discrete and can be represented in the form of frequency , as word count ... 3-GaussianNB -> when all the features are continuous bcz of assumption of normal distribution , and the data can not be represented in frequency i.e., sepal width and height are continous not be in form of frequency ...

In [1]:
import pandas as pd
import numpy as np

# Email_Spam_Detection_Data_Set

In [2]:
df=pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.shape

(5572, 2)

In [4]:
df["Spam"]=df.Category.apply(lambda x : 1 if x=="spam" else 0 )
df.head()

Category                                            Message  Spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [5]:
df = df.drop('Category',axis=1)
df.head()

Message  Spam
0  Go until jurong point, crazy.. Available only ...     0
1                      Ok lar... Joking wif u oni...     0
2  Free entry in 2 a wkly comp to win FA Cup fina...     1
3  U dun say so early hor... U c already then say...     0
4  Nah I don't think he goes to usf, he lives aro...     0

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(df.Message,df.Spam,test_size=0.2)

In [8]:
len(X_train)

4457

In [9]:
len(X_test)

1115

In [10]:
from sklearn.naive_bayes import MultinomialNB

In [11]:
model = MultinomialNB()

Ab data tw text hai aur model text pe ni ... So convert ... 

In [12]:
from sklearn.feature_extraction.text import CountVectorizer # .text bcz text mai se features extract

In [ ]:
CountVectorizer har document mai jitne unique word hote un ko collect aur as a feature leta hai aur matrix create 

In [13]:
v = CountVectorizer()
message_word_count = v.fit_transform(X_train)
message_word_count

<4457x7692 sparse matrix of type '<class 'numpy.int64'>'
	with 59042 stored elements in Compressed Sparse Row format>

In [14]:
message_word_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [15]:
message_word_count.shape

(4457, 7692)

In [16]:
model.fit(message_word_count,y_train)

MultinomialNB()

In [17]:
message_word_count_test = v.transform(X_test)  # agr yahan pr fit_transform tw shape change aur data inconsistent with that it is trained ... 
message_word_count_test.toarray()
message_word_count_test.shape

(1115, 7692)

In [18]:
model.score(message_word_count_test,y_test)

0.9847533632286996

In [22]:
email = [
    
    "Hello Friend , can you please make me to understand the assignmet of COAl",
    "Hello Asim , there is discount on the event of EID on new arrivals",
    "Upto 20 % off on parking in the mall during 5 to 8 pm",
    "Had your mobile 11 months or more? U R entitled to Update to the latest colour mobiles with camera for Free! Call The Mobile Update Co FREE on 08002986030"
    
]

In [23]:
email

['Hello Friend , can you please make me to understand the assignmet of COAl',
 'Hello Asim , there is discount on the event of EID on new arrivals',
 'Upto 20 % off on parking in the mall during 5 to 8 pm',
 'Had your mobile 11 months or more? U R entitled to Update to the latest colour mobiles with camera for Free! Call The Mobile Update Co FREE on 08002986030']

In [24]:
email_count = v.transform(email)
email_count.toarray()
email_count.shape

(4, 7692)

In [25]:
model.predict(email_count)

array([0, 0, 0, 1], dtype=int64)

Ab hamein bar bar CountVectorizer aur phir model run ... Is se bachne k liye ... Pipeline

In [26]:
from sklearn.pipeline import Pipeline

**Hum wo tasks define in steps kh jab text / data dein is pipline ko tw wo step wise run**

In [27]:
clf = Pipeline([
    ("v",CountVectorizer()),
    ("model",MultinomialNB())
])

In [32]:
clf.fit(X_train,y_train)

Pipeline(steps=[('v', CountVectorizer()), ('model', MultinomialNB())])

In [33]:
clf.score(X_test,y_test)

0.9847533632286996

In [34]:
clf.predict(email)  # Ab ek hi step mai 

array([0, 0, 0, 1], dtype=int64)

Perform thesame work on WINE DATA SET for classify 3 categories and apply both GaussianNB & MultinomialNB and measure which gives the highest score

**So , this also appies on classification types problems ...**